/*
 * HARDWARE SETUP the MJD components:
 *  *NONE
 *
 */
#include <float.h>
#include <inttypes.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"

// This header file is generated by 'make menuconfig' and derived from the config file 'sdkconfig'
#include "sdkconfig.h"

#include "esp_event_loop.h"
#include "esp_clk.h"
#include "esp_log.h"
#include "esp_sleep.h"
#include "esp_spi_flash.h"
#include "esp_system.h"

#include "cJSON.h"
#include "driver/i2c.h"
#include "driver/rmt.h"
#include "driver/uart.h"
#include "mbedtls/base64.h"
#include "nvs_flash.h"
#include "soc/rmt_reg.h"
#include "soc/soc.h"

/*
 * Logging
 */
static const char TAG[] = "myapp";

/**********
 * RTOS
 */
#define RTOS_DELAY_0             (0)
#define RTOS_DELAY_1SEC          (1 * 1000 / portTICK_PERIOD_MS)
#define RTOS_DELAY_5SEC          (5 * 1000 / portTICK_PERIOD_MS)
#define RTOS_DELAY_MAX           (portMAX_DELAY)

/*
 * FreeRTOS settings
 */
#define RTOS_TASK_PRIORITY_NORMAL (5)
#define MYAPP_RTOS_TASK_STACK_SIZE_8K (8192)
#define MYAPP_RTOS_TASK_PRIORITY_NORMAL (RTOS_TASK_PRIORITY_NORMAL)

/*
 * HELpERS
 */

/**********
 * MJD strip
 */
uint32_t mjd_seconds_to_microseconds(uint32_t seconds) {
    return seconds * 1000 * 1000;
}

/**********
 * ESP32: BOOT INFO, DEEP SLEEP and WAKE UP
 */
RTC_DATA_ATTR static uint32_t mcu_boot_count = 0; // @important Is a persistent data area after a deep sleep restart)

uint32_t mjd_increment_mcu_boot_count() {
    return ++mcu_boot_count;
}

void mjd_log_mcu_boot_count() {
    ESP_LOGI(TAG, "***(RTC_DATA_ATTR static uint32_t mcu_boot_count): %u\n", mcu_boot_count);
}

uint32_t mjd_get_mcu_boot_count() {
    return mcu_boot_count;
}

void mjd_log_wakeup_details() {
    /*
     * verify the wakeup reason
     * esp_sleep.h
     ESP_SLEEP_WAKEUP_UNDEFINED,    //! In case of deep sleep, reset was not caused by exit from deep sleep
     ESP_SLEEP_WAKEUP_EXT0,         //! Wakeup caused by external signal using RTC_IO
     ESP_SLEEP_WAKEUP_EXT1,         //! Wakeup caused by external signal using RTC_CNTL
     ESP_SLEEP_WAKEUP_TIMER,        //! Wakeup caused by timer
     ESP_SLEEP_WAKEUP_TOUCHPAD,     //! Wakeup caused by touchpad
     ESP_SLEEP_WAKEUP_ULP,          //! Wakeup caused by ULP program
     */
    char wakeup_reason[128];

    switch (esp_sleep_get_wakeup_cause()) {
    case ESP_SLEEP_WAKEUP_EXT0:
        strcpy(wakeup_reason, "EXT0 RTC_IO");
        break;

    case ESP_SLEEP_WAKEUP_EXT1:
        strcpy(wakeup_reason, "EXT1 RTC_CNTL");
        break;

    case ESP_SLEEP_WAKEUP_TIMER:
        strcpy(wakeup_reason, "TIMER");
        break;

    case ESP_SLEEP_WAKEUP_TOUCHPAD:
        strcpy(wakeup_reason, "TOUCHPAD");
        break;

    case ESP_SLEEP_WAKEUP_ULP:
        strcpy(wakeup_reason, "ULP");
        break;

    default:
        strcpy(wakeup_reason, "UNKNOWN (not after a deep sleep period, probably after a normal reset)");
        break;
    }

    ESP_LOGI(TAG, "*** Wakeup reason: %s", wakeup_reason);
}

/*
 * TASK
 */
void main_task(void *pvParameter) {
    ESP_LOGI(TAG, "%s()", __FUNCTION__);

    /********************************************************************************
     * Reuseable variables
     *
     */
    esp_err_t f_retval;

    /********************************************************************************
     * SOC init
     *
     */

    mjd_log_wakeup_details();
    mjd_increment_mcu_boot_count();
    mjd_log_mcu_boot_count();

    /********************************************************************************
     * DEEP SLEEP & RESTART TIMER
     * @sop Put this section in comments when testing other things afterwards (else the MCU restarts every time...)
     * @important In deep sleep mode, wireless peripherals are powered down. Before entering sleep mode, applications must disable WiFi and BT using appropriate calls ( esp_bluedroid_disable(), esp_bt_controller_disable(), esp_wifi_stop()).
     * @doc https://esp-idf.readthedocs.io/en/latest/api-reference/system/sleep_modes.html
     *
     */
    ESP_LOGI(TAG, "\n\n***SECTION: DEEP SLEEP***");

    const uint32_t MY_DEEP_SLEEP_TIME_SEC = 10;
    f_retval = esp_sleep_enable_timer_wakeup(mjd_seconds_to_microseconds(MY_DEEP_SLEEP_TIME_SEC));
    if (f_retval != ESP_OK) {
        ESP_LOGE(TAG, "esp_sleep_enable_timer_wakeup() err %i (%s)", f_retval, esp_err_to_name(f_retval));
        vTaskDelay(RTOS_DELAY_5SEC);
        // GOTO
        goto cleanup;
    }

    // @important Wait a bit so that the ESP_LOGI() can really dump to UART before deep sleep kicks in!
    ESP_LOGI(TAG, "Entering deep sleep (the MCU should wake up %u seconds later)...\n\n", MY_DEEP_SLEEP_TIME_SEC);
    vTaskDelay(RTOS_DELAY_1SEC);

    esp_deep_sleep_start(); // void

    // DEVTEMP @important I never get to this code line if deep sleep is initiated :P
    /////mjd_rtos_wait_forever();

    // LABEL
    cleanup:;

    /********************************************************************************
     * Task Delete
     * @doc Passing NULL will end the current task
     *
     */
    vTaskDelete(NULL);
}

/*
 * MAIN
 */
void app_main() {
    /**********
     * TASK:
     * @important For stability (RMT + Wifi): always use xTaskCreatePinnedToCore(APP_CPU_NUM) [Opposed to xTaskCreate()]
     */
    BaseType_t xReturned;
    xReturned = xTaskCreatePinnedToCore(&main_task, "main_task (name)", MYAPP_RTOS_TASK_STACK_SIZE_8K, NULL,
    MYAPP_RTOS_TASK_PRIORITY_NORMAL, NULL,
    APP_CPU_NUM);
    if (xReturned == pdPASS) {
        ESP_LOGI(TAG, "OK Task has been created, and is running right now");
    }

    /**********
     * END
     */
    ESP_LOGI(TAG, "END %s()", __FUNCTION__);
}
